colors = ['red', 'blue', 'yellow']
print(colors)
numbers_list = ((1, 2, 3, 4, 5))
print((numbers_list))
r = list(range(1, 50))
print(r)
# esto es un test de variable list
#print(dir(colors))
#print(len(colors))
#print(len(r))
#print(colors[-3])
colors.extend(['brown', 'green', 'withe'])
print(colors)
#colors.insert(-1, ' black')
#print(colors)
colors.insert(len(colors), 'orange')
print(colors)
colors.sort(reverse=True)
print(colors)
z = (1)
print(type(z))
